Repository Morphclue/apollusia, pull requests merged in 2023-11, with the labels that each got.

#94 Jetbrains - Apollusia Logo
  .idea/icon.svg
Labels: enhancement

#95 Imprint
  README.md
  apps/backend/src/app.module.ts
  apps/backend/src/imprint/imprint.module.ts
  apps/backend/src/imprint/imprint/imprint.controller.ts
  apps/backend/src/imprint/imprint/imprint.service.ts
  apps/frontend/src/app/legal/legal.module.ts
  apps/frontend/src/app/legal/legal/legal.component.html
  apps/frontend/src/app/legal/legal/legal.component.ts
  apps/frontend/src/app/legal/services/imprint.service.ts
  libs/types/src/lib/dto/imprint.dto.ts
  libs/types/src/lib/dto/index.ts
Labels: frontend, backend

#97 Ensure admin check completes before (not) showing blind poll results
  apps/frontend/src/app/poll/choose-events/choose-events.component.ts
  package.json
  pnpm-lock.yaml
Labels: bug, enhancement
