Repository Morphclue/apollusia, pull requests merged in 2024-04, with the labels that each got.

#148 ESBuild
  apps/frontend/project.json
  apps/frontend/server.ts
  apps/frontend/src/app/app.component.ts
  apps/frontend/src/app/app.module.ts
  apps/frontend/src/app/app.server.module.ts
  apps/frontend/src/app/core/info-table/info-table.component.ts
  apps/frontend/src/app/poll/choose-events/choose-events.component.ts
  apps/frontend/src/main.server.ts
  apps/frontend/src/polyfills.ts
  apps/frontend/src/styles.scss
  apps/frontend/tsconfig.app.json
  apps/frontend/tsconfig.json
  apps/frontend/tsconfig.server.json
  libs/types/tsconfig.lib.json
  tsconfig.base.json
Labels: frontend

#149 Minor Frontend Fixes
  apps/frontend/Dockerfile
  apps/frontend/project.json
  apps/frontend/server.ts
  apps/frontend/src/app/core/navbar/navbar.component.html
  apps/frontend/src/app/core/navbar/navbar.component.scss
  apps/frontend/src/app/settings/token/token.component.html
  apps/frontend/src/app/settings/token/token.component.ts
  package.json
  pnpm-lock.yaml
Labels: bug, frontend

#150 Fix missing event population
  apps/backend/src/poll/poll/poll.service.ts
Labels: bug, frontend

#153 Update Dependencies and Time Display
  apps/frontend/src/app/poll/choose-events/choose-events.component.html
  apps/frontend/src/app/poll/choose-events/choose-events.component.ts
  apps/frontend/src/app/poll/event-head/event-head.component.html
  package.json
  pnpm-lock.yaml
Labels: bug, dependencies

#152 Show results after deadline
  apps/backend/src/poll/poll/poll.service.ts
  apps/frontend/src/app/poll/choose-events/choose-events.component.ts
  apps/frontend/src/app/poll/create-poll/create-edit-poll.component.html
  libs/types/src/lib/schema/show-result-options.ts
Labels: enhancement
