Repository Morphclue/apollusia, pull requests merged in 2024-05, with the labels that each got.

#160 Keycloak dev image
  docker-compose.yml
Labels: enhancement

#162 Fix unknown change events
  apps/backend/src/poll/poll/poll.controller.ts
  apps/backend/src/poll/poll/poll.service.ts
  apps/frontend/src/app/poll/choose-events/choose-events.component.html
  apps/frontend/src/app/poll/table/table.component.html
  apps/frontend/src/app/poll/table/table.component.ts
  libs/types/src/lib/schema/poll-event.schema.ts
Labels: bug, backend

#164 Custom Duration / Calendar Segments
  apps/frontend/src/app/poll/choose-date/choose-date.component.html
  apps/frontend/src/app/poll/choose-date/choose-date.component.ts
  apps/frontend/src/app/poll/services/choose-date.service.ts
Labels: enhancement, frontend

#168 Update Nx and Dependencies
  .github/workflows/audit.yaml
  .github/workflows/test.yml
  apps/backend/Dockerfile
  apps/backend/src/poll/poll/poll.service.ts
  apps/frontend/Dockerfile
  package.json
  pnpm-lock.yaml
Labels: dependencies

#165 Book Individual Participants
  apps/backend/src/poll/poll/poll.controller.ts
  apps/backend/src/poll/poll/poll.service.ts
  apps/backend/test/stubs/PollStub.ts
  apps/frontend/src/app/pipes/some.pipe.ts
  apps/frontend/src/app/poll/create-poll/create-edit-poll.component.ts
  apps/frontend/src/app/poll/ical/ical.component.ts
  apps/frontend/src/app/poll/services/poll.service.ts
  apps/frontend/src/app/poll/table/table.component.html
  apps/frontend/src/app/poll/table/table.component.scss
  apps/frontend/src/app/poll/table/table.component.ts
  libs/types/src/lib/schema/poll.schema.ts
Labels: enhancement

#166 Add Push Config Endpoint
  apps/backend/src/push/push.controller.ts
  apps/backend/src/push/push.module.ts
  apps/backend/src/push/push.service.ts
  apps/frontend/src/app/poll/create-poll/create-edit-poll.component.ts
  apps/frontend/src/app/poll/services/push.service.ts
  apps/frontend/src/environments/environment.prod.ts
  apps/frontend/src/environments/environment.ts
  libs/types/src/lib/dto/index.ts
  libs/types/src/lib/dto/push.dto.ts
Labels: enhancement

#167 Show Version in Frontend
  .dockerignore
  .github/workflows/deploy.sh
  .github/workflows/deploy.yml
  apps/frontend/Dockerfile
  apps/frontend/plugins/define-version.cjs
  apps/frontend/project.json
  apps/frontend/src/app/core/navbar/navbar.component.html
  apps/frontend/src/app/core/navbar/navbar.component.ts
  apps/frontend/src/types.d.ts
Labels: enhancement

#170 Keycloak theme
  .gitignore
  .stylelintrc.json
  docker-compose.yml
  libs/keycloak/.gitignore
  libs/keycloak/.stylelintrc.json
  libs/keycloak/common/resources/img/favicon.ico
  libs/keycloak/login/theme.properties
  libs/keycloak/project.json
  libs/keycloak/src/theme.scss
  nx.json
  package.json
  pnpm-lock.yaml
Labels: frontend
