Repository Morphclue/apollusia, pull requests merged in 2024-07, with the labels that each got.

#176 Autofill note
  apps/frontend/src/app/modals/autofill-modal/autofill-modal.component.html
  apps/frontend/src/app/modals/autofill-modal/autofill-modal.component.ts
  apps/frontend/src/app/poll/services/choose-date.service.ts
Labels: enhancement, frontend

#178 Keycloak Account Login
  apps/frontend/src/app/app.module.ts
  apps/frontend/src/app/core/navbar/navbar.component.html
  apps/frontend/src/app/core/navbar/navbar.component.ts
  apps/frontend/src/assets/silent-check-sso.html
  apps/frontend/src/environments/environment.prod.ts
  apps/frontend/src/environments/environment.ts
  package.json
  pnpm-lock.yaml
Labels: enhancement

#179 Keycloak Backend Integration
  apps/backend/src/app.module.ts
  apps/backend/src/auth/optional-auth.guard.ts
  apps/backend/src/environment.ts
  apps/backend/src/poll/poll/poll.controller.ts
  apps/backend/src/poll/poll/poll.service.ts
  libs/types/src/lib/schema/participant.schema.ts
  libs/types/src/lib/schema/poll.schema.ts
  package.json
  pnpm-lock.yaml
Labels: enhancement

#174 Fix line break in card url
  apps/frontend/src/app/core/info-table/info-table.component.html
  apps/frontend/src/app/core/info-table/info-table.component.scss
Labels: bug, frontend

#180 Fix Frontend Build and Keycloak Reliance
  apps/frontend/src/app/app.module.ts
  package.json
  pnpm-lock.yaml
Labels: bug

#181 Claim Polls & Advertise Accounts
  apps/backend/src/poll/poll/poll.controller.ts
  apps/backend/src/poll/poll/poll.service.ts
  apps/frontend/src/app/core/navbar/navbar.component.html
  apps/frontend/src/app/dashboard/dashboard/dashboard.component.html
  apps/frontend/src/app/dashboard/dashboard/dashboard.component.ts
  apps/frontend/src/app/poll/services/poll.service.ts
  apps/frontend/src/assets/artwork/account.svg
Labels: enhancement

#183 Add NgxCookieService required provider
  apps/frontend/server.ts
Labels: bug

#182 Refactor Poll Service
  apps/backend/src/app.module.ts
  apps/backend/src/participant/participant.controller.ts
  apps/backend/src/participant/participant.module.ts
  apps/backend/src/participant/participant.service.ts
  apps/backend/src/poll-event/poll-event.controller.ts
  apps/backend/src/poll-event/poll-event.module.ts
  apps/backend/src/poll-event/poll-event.service.ts
  apps/backend/src/poll/poll-actions.service.spec.ts
  apps/backend/src/poll/poll-actions.service.ts
  apps/backend/src/poll/poll.controller.ts
  apps/backend/src/poll/poll.module.ts
  apps/backend/src/poll/poll/poll.controller.ts
  package.json
  pnpm-lock.yaml
Labels: enhancement, backend
